apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chroma
  labels:
    cloud.googleapis.com/location: us-west1
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: all
    run.googleapis.com/maxScale: '1'
    run.googleapis.com/minScale: '0'

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: chroma-db-service@image-retrieval-459422.iam.gserviceaccount.com
      containers:
      - image: chromadb/chroma
        ports:
        - containerPort: 8000
        env:
        - name: CHROMA_SERVER_AUTHN_CREDENTIALS
          value: oLJcki8YCnfRsqFsNMllbX51HgHX49Bl
        - name: CHROMA_SERVER_AUTHN_PROVIDER
          value: chromadb.auth.token_authn.TokenAuthenticationServerProvider
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: /data
        - name: ALLOW_RESET
          value: "FALSE"
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
        - name: gcs-1
          mountPath: /data
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8000
      volumes:
      - name: gcs-1
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: false
          volumeAttributes:
            bucketName: face-embeddings
            mountOptions: "implicit-dirs,file-mode=777,dir-mode=777,uid=1000,gid=1000,debug_gcs,debug_fuse,debug_fuse_errors"
  traffic:
  - percent: 100
    latestRevision: true